/**
 * This class is generated by jOOQ
 */
package de.schandera.jenkins_tryout.GeneratedClasses;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in guestbook
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table guestbook.posts
	 */
	public static final de.schandera.jenkins_tryout.GeneratedClasses.tables.Posts POSTS = de.schandera.jenkins_tryout.GeneratedClasses.tables.Posts.POSTS;
}
