/**
 * This class is generated by jOOQ
 */
package de.schandera.jenkins_tryout.GeneratedClasses.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = { "http://www.jooq.org", "3.1.0" }, comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Posts extends
		org.jooq.impl.TableImpl<de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord> {

	private static final long serialVersionUID = -1853952226;

	/**
	 * The singleton instance of <code>guestbook.posts</code>
	 */
	public static final de.schandera.jenkins_tryout.GeneratedClasses.tables.Posts POSTS = new de.schandera.jenkins_tryout.GeneratedClasses.tables.Posts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord> getRecordType() {
		return de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord.class;
	}

	/**
	 * The column <code>guestbook.posts.id</code>.
	 */
	public final org.jooq.TableField<de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord, java.lang.Long> ID = createField(
			"id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>guestbook.posts.body</code>.
	 */
	public final org.jooq.TableField<de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord, java.lang.String> BODY = createField(
			"body", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>guestbook.posts.timestamp</code>.
	 */
	public final org.jooq.TableField<de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord, java.sql.Timestamp> TIMESTAMP = createField(
			"timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>guestbook.posts.title</code>.
	 */
	public final org.jooq.TableField<de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord, java.lang.String> TITLE = createField(
			"title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>guestbook.posts</code> table reference
	 */
	public Posts() {
		super("posts", de.schandera.jenkins_tryout.GeneratedClasses.Guestbook.GUESTBOOK);
	}

	/**
	 * Create an aliased <code>guestbook.posts</code> table reference
	 */
	public Posts(java.lang.String alias) {
		super(alias, de.schandera.jenkins_tryout.GeneratedClasses.Guestbook.GUESTBOOK,
				de.schandera.jenkins_tryout.GeneratedClasses.tables.Posts.POSTS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord> getPrimaryKey() {
		return de.schandera.jenkins_tryout.GeneratedClasses.Keys.KEY_POSTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord>> getKeys() {
		return java.util.Arrays
				.<org.jooq.UniqueKey<de.schandera.jenkins_tryout.GeneratedClasses.tables.records.PostsRecord>> asList(de.schandera.jenkins_tryout.GeneratedClasses.Keys.KEY_POSTS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.schandera.jenkins_tryout.GeneratedClasses.tables.Posts as(java.lang.String alias) {
		return new de.schandera.jenkins_tryout.GeneratedClasses.tables.Posts(alias);
	}
}
